// Smart Shopping List Manager for AI Food Waste Reduction Agent - Indian Version
import { Storage } from "./storage.js";
import { Notifications } from "./notifications.js";

// Standard shelf life approximations by Indian food keywords for smart import
const SHELF_LIFE_ESTIMATES = {
  paneer: { category: "Dairy", days: 4, unit: "pack" },
  coriander: { category: "Vegetables", days: 5, unit: "pcs" },
  dhaniya: { category: "Vegetables", days: 5, unit: "pcs" },
  milk: { category: "Dairy", days: 3, unit: "pack" },
  bread: { category: "Grains/Pantry", days: 5, unit: "loaf" },
  egg: { category: "Dairy", days: 14, unit: "dozen" },
  tomato: { category: "Fruits", days: 6, unit: "pack" },
  potato: { category: "Grains/Pantry", days: 20, unit: "pack" },
  aloo: { category: "Grains/Pantry", days: 20, unit: "pack" },
  ginger: { category: "Vegetables", days: 30, unit: "pack" },
  curd: { category: "Dairy", days: 6, unit: "pack" },
  dahi: { category: "Dairy", days: 6, unit: "pack" },
  chillies: { category: "Vegetables", days: 15, unit: "pack" },
  onion: { category: "Vegetables", days: 30, unit: "pack" },
  pyaaz: { category: "Vegetables", days: 30, unit: "pack" },
  atta: { category: "Grains/Pantry", days: 90, unit: "pack" }
};

export const ShoppingManager = {
  init() {
    this.render();
    this.setupListeners();
  },

  setupListeners() {
    const form = document.getElementById("shopping-add-form");
    if (form) {
      form.addEventListener("submit", (e) => {
        e.preventDefault();
        this.handleManualAdd(form);
      });
    }

    const autoGenBtn = document.getElementById("btn-auto-generate-shopping");
    if (autoGenBtn) {
      autoGenBtn.addEventListener("click", () => {
        this.autoGenerateNeededItems();
      });
    }

    const clearBtn = document.getElementById("btn-clear-completed-shopping");
    if (clearBtn) {
      clearBtn.addEventListener("click", () => {
        this.clearCompleted();
      });
    }

    const importBtn = document.getElementById("btn-import-shopping-pantry");
    if (importBtn) {
      importBtn.addEventListener("click", () => {
        this.openImportModal();
      });
    }

    const importModal = document.getElementById("shopping-import-modal");
    if (importModal) {
      importModal.querySelector(".modal-close").addEventListener("click", () => {
        importModal.style.display = "none";
      });
    }
  },

  render() {
    const container = document.getElementById("shopping-list-items");
    if (!container) return;

    const list = Storage.getShopping();
    container.innerHTML = "";

    const hasItems = list.length > 0;
    const hasCompleted = list.some(item => item.checked);
    
    const importBtn = document.getElementById("btn-import-shopping-pantry");
    const clearBtn = document.getElementById("btn-clear-completed-shopping");

    if (importBtn) importBtn.disabled = !hasCompleted;
    if (clearBtn) clearBtn.disabled = !hasCompleted;

    if (!hasItems) {
      container.innerHTML = `
        <div class="empty-state">
          <i data-lucide="shopping-cart" class="empty-icon"></i>
          <h3>Your shopping list is empty</h3>
          <p>Add items manually, or click 'AI Auto-Generate' to scan pantry levels.</p>
        </div>
      `;
      if (window.lucide) window.lucide.createIcons();
      return;
    }

    list.forEach(item => {
      const row = document.createElement("div");
      row.className = `shopping-item-row ${item.checked ? 'checked' : ''}`;
      
      const badgeHtml = item.autoGenerated 
        ? `<span class="shopping-item-badge"><i data-lucide="sparkles" class="badge-icon"></i> Smart Suggestion</span>` 
        : "";

      row.innerHTML = `
        <label class="shopping-item-checkbox-container">
          <input type="checkbox" class="shopping-item-checkbox" data-id="${item.id}" ${item.checked ? 'checked' : ''}>
          <span class="custom-checkbox"></span>
        </label>
        
        <div class="shopping-item-details">
          <span class="shopping-item-name">${item.name}</span>
          <span class="shopping-item-qty">${item.qty} ${item.unit}</span>
          ${badgeHtml}
        </div>
        
        <button class="shopping-item-delete-btn" data-id="${item.id}">
          <i data-lucide="trash"></i>
        </button>
      `;

      row.querySelector(".shopping-item-checkbox").addEventListener("change", (e) => {
        this.toggleCheck(item.id, e.target.checked);
      });

      row.querySelector(".shopping-item-delete-btn").addEventListener("click", () => {
        this.deleteItem(item.id);
      });

      container.appendChild(row);
    });

    if (window.lucide) {
      window.lucide.createIcons();
    }
  },

  handleManualAdd(form) {
    const name = form.querySelector("#shopping-name").value.trim();
    const qty = parseFloat(form.querySelector("#shopping-qty").value);
    const unit = form.querySelector("#shopping-unit").value;

    if (!name || isNaN(qty)) {
      Notifications.showToast("Please enter an item name and valid quantity", "error");
      return;
    }

    const list = Storage.getShopping();
    list.push({
      id: "s_" + Date.now(),
      name,
      qty,
      unit,
      checked: false,
      autoGenerated: false
    });

    Storage.setShopping(list);
    this.render();
    form.reset();
    Notifications.showToast(`Added ${name} to shopping list!`, "success");
  },

  toggleCheck(id, isChecked) {
    const list = Storage.getShopping();
    const item = list.find(i => i.id === id);
    if (item) {
      item.checked = isChecked;
      Storage.setShopping(list);
      this.render();
    }
  },

  deleteItem(id) {
    const list = Storage.getShopping();
    const filtered = list.filter(i => i.id !== id);
    Storage.setShopping(filtered);
    this.render();
    Notifications.showToast("Item removed from list", "info");
  },

  clearCompleted() {
    const list = Storage.getShopping();
    const filtered = list.filter(i => !i.checked);
    Storage.setShopping(filtered);
    this.render();
    Notifications.showToast("Cleared checked shopping list items", "info");
  },

  autoGenerateNeededItems() {
    const pantry = Storage.getPantry();
    const shopping = Storage.getShopping();
    let suggestionsCount = 0;

    pantry.forEach(item => {
      const percentLeft = item.qty / (item.originalQty || 1);
      if (percentLeft <= 0.25) {
        const exists = shopping.some(s => s.name.toLowerCase() === item.name.toLowerCase());
        if (!exists) {
          shopping.push({
            id: "s_auto_" + Math.random().toString(36).substr(2, 9),
            name: item.name,
            qty: item.originalQty || 1,
            unit: item.unit,
            checked: false,
            autoGenerated: true
          });
          suggestionsCount++;
        }
      }
    });

    const logs = Storage.getLogs();
    const consumedFrequencies = {};
    logs.forEach(log => {
      if (log.status === "consumed") {
        consumedFrequencies[log.name] = (consumedFrequencies[log.name] || 0) + 1;
      }
    });

    Object.keys(consumedFrequencies).forEach(itemName => {
      const inPantry = pantry.some(p => p.qty > 0 && p.name.toLowerCase() === itemName.toLowerCase());
      const inShopping = shopping.some(s => s.name.toLowerCase() === itemName.toLowerCase());

      if (consumedFrequencies[itemName] >= 2 && !inPantry && !inShopping) {
        const shelfDef = Object.keys(SHELF_LIFE_ESTIMATES).find(k => itemName.toLowerCase().includes(k)) 
          ? SHELF_LIFE_ESTIMATES[Object.keys(SHELF_LIFE_ESTIMATES).find(k => itemName.toLowerCase().includes(k))]
          : { category: "Others", days: 7, unit: "pcs" };

        shopping.push({
          id: "s_auto_hist_" + Math.random().toString(36).substr(2, 9),
          name: itemName,
          qty: 1,
          unit: shelfDef.unit,
          checked: false,
          autoGenerated: true
        });
        suggestionsCount++;
      }
    });

    if (suggestionsCount > 0) {
      Storage.setShopping(shopping);
      this.render();
      Notifications.showToast(`AI analysis completed: suggested ${suggestionsCount} depleted or common pantry items!`, "success");
    } else {
      Notifications.showToast("Your pantry is well stocked! No auto-generations needed currently.", "info");
    }
  },

  openImportModal() {
    const modal = document.getElementById("shopping-import-modal");
    if (!modal) return;

    const list = Storage.getShopping();
    const checkedItems = list.filter(item => item.checked);
    
    if (checkedItems.length === 0) return;

    const container = modal.querySelector("#import-modal-items");
    container.innerHTML = "";

    const today = new Date().toISOString().split("T")[0];

    checkedItems.forEach((item, index) => {
      let defaultCat = "Others";
      let defaultDays = 7;

      const lowerName = item.name.toLowerCase();
      const matchKey = Object.keys(SHELF_LIFE_ESTIMATES).find(key => lowerName.includes(key));
      if (matchKey) {
        defaultCat = SHELF_LIFE_ESTIMATES[matchKey].category;
        defaultDays = SHELF_LIFE_ESTIMATES[matchKey].days;
      }

      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + defaultDays);
      const expiryStr = futureDate.toISOString().split("T")[0];

      const itemBlock = document.createElement("div");
      itemBlock.className = "import-item-block mb-3 p-3 border rounded border-secondary bg-dark-card";
      itemBlock.innerHTML = `
        <div class="row align-items-center">
          <div class="col-md-4">
            <h5 class="mb-1 text-light">${item.name}</h5>
            <span class="small text-muted">${item.qty} ${item.unit}</span>
          </div>
          <div class="col-md-4">
            <label class="form-label small text-muted">Category</label>
            <select class="form-control form-control-sm import-item-cat" data-index="${index}">
              <option value="Vegetables" ${defaultCat === "Vegetables" ? "selected" : ""}>Vegetables</option>
              <option value="Fruits" ${defaultCat === "Fruits" ? "selected" : ""}>Fruits</option>
              <option value="Dairy" ${defaultCat === "Dairy" ? "selected" : ""}>Dairy</option>
              <option value="Meat/Seafood">Meat/Seafood</option>
              <option value="Grains/Pantry" ${defaultCat === "Grains/Pantry" ? "selected" : ""}>Grains/Pantry</option>
              <option value="Others" ${defaultCat === "Others" ? "selected" : ""}>Others</option>
            </select>
          </div>
          <div class="col-md-4">
            <label class="form-label small text-muted">Expiry Date</label>
            <input type="date" class="form-control form-control-sm import-item-expiry" data-index="${index}" value="${expiryStr}" min="${today}">
          </div>
        </div>
      `;

      itemBlock._data = item;
      container.appendChild(itemBlock);
    });

    const confirmBtn = modal.querySelector("#btn-confirm-import-shopping");
    confirmBtn.onclick = () => {
      this.executeImport(modal);
    };

    modal.style.display = "block";
  },

  executeImport(modal) {
    const blocks = modal.querySelectorAll(".import-item-block");
    const pantry = Storage.getPantry();
    const shopping = Storage.getShopping();
    let importedCount = 0;

    blocks.forEach(block => {
      const shoppingItem = block._data;
      const catSelect = block.querySelector(".import-item-cat");
      const dateInput = block.querySelector(".import-item-expiry");

      const category = catSelect.value;
      const expiryDate = dateInput.value;

      pantry.push({
        id: "p_sh_" + Date.now() + "_" + Math.random().toString(36).substr(2, 5),
        name: shoppingItem.name,
        category: category,
        qty: shoppingItem.qty,
        unit: shoppingItem.unit,
        expiryDate: expiryDate,
        originalQty: shoppingItem.qty,
        addedDate: new Date().toISOString().split("T")[0],
        consumedQty: 0,
        wastedQty: 0
      });

      const idx = shopping.findIndex(s => s.id === shoppingItem.id);
      if (idx !== -1) {
        shopping.splice(idx, 1);
      }

      importedCount++;
    });

    Storage.setPantry(pantry);
    Storage.setShopping(shopping);
    
    modal.style.display = "none";
    this.render();
    
    Notifications.showToast(`Imported ${importedCount} items from shopping list to pantry!`, "success");
  }
};
