// Storage Manager for AI Food Waste Reduction Agent - Indian Version

const STORAGE_KEYS = {
  PANTRY: "waste_agent_pantry",
  SHOPPING: "waste_agent_shopping",
  LOGS: "waste_agent_logs",
  USER_STATS: "waste_agent_user_stats",
  CHAT_HISTORY: "waste_agent_chat_history"
};

// Seeding Indian staples
const DEFAULT_PANTRY = [
  { id: "p1", name: "Amul Fresh Paneer 200g", category: "Dairy", qty: 1, unit: "pack", expiryDate: getOffsetDate(2), originalQty: 1, addedDate: getOffsetDate(-2), consumedQty: 0, wastedQty: 0, status: "Expiring" },
  { id: "p2", name: "Fresh Coriander Bunch 100g", category: "Vegetables", qty: 1, unit: "pcs", expiryDate: getOffsetDate(1), originalQty: 1, addedDate: getOffsetDate(-3), consumedQty: 0, wastedQty: 0, status: "Expiring" },
  { id: "p3", name: "Nandini Toned Milk 500ml", category: "Dairy", qty: 0.5, unit: "pack", expiryDate: getOffsetDate(3), originalQty: 1, addedDate: getOffsetDate(-1), consumedQty: 0.5, wastedQty: 0, status: "Fresh" },
  { id: "p4", name: "Harvest Gold Brown Bread", category: "Grains/Pantry", qty: 6, unit: "slices", expiryDate: getOffsetDate(-1), originalQty: 12, addedDate: getOffsetDate(-5), consumedQty: 6, wastedQty: 0, status: "Expired" }
];

const DEFAULT_SHOPPING = [
  { id: "s1", name: "Ooty Potatoes (Aloo) 1kg", qty: 1, unit: "pack", checked: false, autoGenerated: false },
  { id: "s2", name: "Fresh Roma Tomatoes 500g", qty: 1, unit: "pack", checked: false, autoGenerated: true }
];

// Historical logs in Indian Rupees (₹)
const DEFAULT_LOGS = [
  { date: getOffsetDateString(-6), name: "Mother Dairy Dahi 400g", category: "Dairy", qty: 1, unit: "pack", value: 65.0, status: "consumed", weight: 0.4 },
  { date: getOffsetDateString(-5), name: "Fresh Coriander Bunch 100g", category: "Vegetables", qty: 1, unit: "pcs", value: 18.0, status: "wasted", weight: 0.1 },
  { date: getOffsetDateString(-4), name: "Harvest Gold Brown Bread", category: "Grains/Pantry", qty: 6, unit: "slices", value: 25.0, status: "consumed", weight: 0.3 },
  { date: getOffsetDateString(-3), name: "Fresh Bananas 1 Dozen", category: "Fruits", qty: 4, unit: "pcs", value: 20.0, status: "consumed", weight: 0.6 },
  { date: getOffsetDateString(-2), name: "Roma Tomatoes 500g", category: "Fruits", qty: 0.5, unit: "pack", value: 32.5, status: "wasted", weight: 0.25 },
  { date: getOffsetDateString(-1), name: "Nandini Toned Milk 500ml", category: "Dairy", qty: 0.5, unit: "pack", value: 13.5, status: "consumed", weight: 0.5 }
];

const DEFAULT_USER_STATS = {
  xp: 320,
  level: 2,
  challenges: [
    { id: "chal1", title: "Weekend Rasoi Warrior", description: "Mark 0 items as 'Wasted' from Friday to Sunday.", xp: 150, progress: 100, completed: true, badge: "badge_zero_waste_week", badgeName: "Rasoi Protector", type: "weekend" },
    { id: "chal2", title: "Chutney Legend", description: "Cook 3 recipes that utilize items expiring within 3 days.", xp: 200, progress: 66, completed: false, badge: "badge_recipe_rescuer", badgeName: "Chutney Rescuer", type: "cook" },
    { id: "chal3", title: "Clean Fridge Purge", description: "Reduce your total pantry items count to below 5 by consuming them.", xp: 100, progress: 40, completed: false, badge: "badge_pantry_master", badgeName: "Clean Plate Master", type: "pantry" }
  ],
  badges: ["badge_zero_waste_week"]
};

const DEFAULT_CHAT = [
  { sender: "chef", message: "Namaste! 🙏 I am Chef Rasoi AI. I can help you rescue ingredients from spoiling, suggest Indian leftover recipes, or tell you how to store fresh dhaniya or green chillies. Try asking: *'What can I cook with paneer?'* or *'How do I store coriander?'*", timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }
];

function getOffsetDate(daysOffset) {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split("T")[0];
}

function getOffsetDateString(daysOffset) {
  return getOffsetDate(daysOffset);
}

export const Storage = {
  init() {
    if (!localStorage.getItem(STORAGE_KEYS.PANTRY)) {
      localStorage.setItem(STORAGE_KEYS.PANTRY, JSON.stringify(DEFAULT_PANTRY));
    }
    if (!localStorage.getItem(STORAGE_KEYS.SHOPPING)) {
      localStorage.setItem(STORAGE_KEYS.SHOPPING, JSON.stringify(DEFAULT_SHOPPING));
    }
    if (!localStorage.getItem(STORAGE_KEYS.LOGS)) {
      localStorage.setItem(STORAGE_KEYS.LOGS, JSON.stringify(DEFAULT_LOGS));
    }
    if (!localStorage.getItem(STORAGE_KEYS.USER_STATS)) {
      localStorage.setItem(STORAGE_KEYS.USER_STATS, JSON.stringify(DEFAULT_USER_STATS));
    }
    if (!localStorage.getItem(STORAGE_KEYS.CHAT_HISTORY)) {
      localStorage.setItem(STORAGE_KEYS.CHAT_HISTORY, JSON.stringify(DEFAULT_CHAT));
    }
  },

  getPantry() {
    return JSON.parse(localStorage.getItem(STORAGE_KEYS.PANTRY)) || [];
  },

  setPantry(items) {
    localStorage.setItem(STORAGE_KEYS.PANTRY, JSON.stringify(items));
    window.dispatchEvent(new CustomEvent("pantryUpdated", { detail: items }));
  },

  getShopping() {
    return JSON.parse(localStorage.getItem(STORAGE_KEYS.SHOPPING)) || [];
  },

  setShopping(items) {
    localStorage.setItem(STORAGE_KEYS.SHOPPING, JSON.stringify(items));
    window.dispatchEvent(new CustomEvent("shoppingUpdated", { detail: items }));
  },

  getLogs() {
    return JSON.parse(localStorage.getItem(STORAGE_KEYS.LOGS)) || [];
  },

  setLogs(logs) {
    localStorage.setItem(STORAGE_KEYS.LOGS, JSON.stringify(logs));
    window.dispatchEvent(new CustomEvent("logsUpdated", { detail: logs }));
  },

  getUserStats() {
    return JSON.parse(localStorage.getItem(STORAGE_KEYS.USER_STATS)) || DEFAULT_USER_STATS;
  },

  setUserStats(stats) {
    localStorage.setItem(STORAGE_KEYS.USER_STATS, JSON.stringify(stats));
    window.dispatchEvent(new CustomEvent("statsUpdated", { detail: stats }));
  },

  getChatHistory() {
    return JSON.parse(localStorage.getItem(STORAGE_KEYS.CHAT_HISTORY)) || [];
  },

  setChatHistory(history) {
    localStorage.setItem(STORAGE_KEYS.CHAT_HISTORY, JSON.stringify(history));
  },

  resetAll() {
    localStorage.removeItem(STORAGE_KEYS.PANTRY);
    localStorage.removeItem(STORAGE_KEYS.SHOPPING);
    localStorage.removeItem(STORAGE_KEYS.LOGS);
    localStorage.removeItem(STORAGE_KEYS.USER_STATS);
    localStorage.removeItem(STORAGE_KEYS.CHAT_HISTORY);
    this.init();
    window.location.reload();
  }
};
